### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by CGamesPlay**
The following error occurs on `0.3.0` when trying to install using yarn:

    error urlsafe-base64@0.0.2: The engine "node" is incompatible with this module. Expected version "0.8.x".

This pull requests resolves this error by upgrading the version of urlsafe-base64. The tests still pass.

### CODE REVIEW

**Comment by ofek** [comment]
Is yarn.lock necessary?

**Comment by CGamesPlay** [comment]
According to the documentation, it's advisable to check it in for CI purposes, but yarn does not reference it outside of the top-level project. https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control

**Comment by EyePulp** [comment]
Can this be bumped in npm?

**Comment by hburrows** [comment]
👍  To updating the dependencies and getting this bumped in npm.

**Pull request merged**
