### PR TITLE
moved the invalid token ttl and far-future timestamp errors to only o…

### PR DESCRIPTION
**Pull request by robertjkeck2**
Similar to this discussion in this [Python Crypto issue](https://github.com/pyca/cryptography/pull/2682), the far-future timestamp should only be checked if the TTL value is not null (a.k.a > 0 in this implementation). This PR moves the `Invalid Token: TTL` and `Error: far-future timestamp` errors into a conditional to test if TTL is > 0.

The tests have also been updated and additional linting was done as well.

### CODE REVIEW

**Comment by robertjkeck2** [comment]
@csquared let me know if you have any questions or if I'd be better of just doing an npm fork if you aren't still maintaining this project!

**Comment by csquared** [comment]
Hey @robertjkeck2 - this change looks good but do you mind restricting it to just the desired functionality (and without all the whitespace changes).
Conversely, if that's a common linter pattern now happy to merge and cut a new release.

**Comment by aditya-toppr** [comment]
These changes are not reflecting in the latest npm lib version(0.3.1). When is this expected to be released in the new version?  
Would really appreciate if this can be released as early as possible.

**Comment by csquared** [comment]
Just released 0.4.0

**Comment by aditya-toppr** [comment]
Thanks @csquared . Really appreciate you releasing it this early.

**Pull request merged**
